# See the mkdocs user guide for more information on these settings.
#   http://www.mkdocs.org/user-guide/configuration/

site_name:        Phylo.jl
repo_url:         https://github.com/richardreeve/Phylo.jl
site_description: Package for creating and manipulating phylogenies
site_author:      Richard Reeve

theme: material

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction:      index.md
- Submodules:
    - API:           api.md
